name: flutter_paisa
description: A expene manager app for Android.

publish_to: 'none'

version: 1.5.0+10

environment:
  sdk: ">=2.17.0-69.0.dev <3.0.0"

dependencies:
  chart_sparkline: ^1.0.8
  charts_flutter: ^0.12.0
  csv: ^5.0.1
  date_picker_timeline: ^1.2.3 
  device_info_plus: ^3.2.1
  dynamic_color: ^0.1.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  #flutter_iconpicker: ^3.1.2
  flutter_local_notifications: ^9.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_timezone: ^2.0.0
  get_it: ^7.2.0
  glassmorphism: ^3.0.0
  google_fonts: ^2.2.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  image_picker: ^0.8.4+4
  intl: ^0.17.0
  local_auth: ^1.1.10
  material_color_utilities: ^0.1.3
  material_design_icons_flutter: ^5.0.6595
  package_info_plus: ^1.3.0
  path_provider: ^2.0.8
  responsive_builder: ^0.4.1
  share_plus: ^3.0.4 
  url_launcher: ^6.0.18
  url_strategy: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.7
  change_app_package_name: any
  flutter_app_name: ^0.1.1
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_native_splash: ^1.3.3
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.1

flutter_app_name:
  name: "Paisa"

flutter_native_splash:
  color: "
  image: assets/images/icon.png
  color_dark: "
  android: true
  ios: true

flutter_icons:
  image_path: "assets/images/icon.png"
  ios: true
  android: false
  

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
